languageCode = "en-us"
title = "Fresh Start"
theme = "crab"
baseurl = "/"

[params]
description = "Everybody deserves a fresh start"
logoimage = "/img/logo.png"
#logoimage = "/img/benzo.jpg"
copyright = "Fresh Start"

# mathjax = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
## Uncomment if you want mathjax enabled. The above cdn source is taken from https://gohugo.io/content-management/formats/#mathjax-with-hugo

[permalinks]
blog  = "/blog/:year/:month/:title/"

[taxonomies]
tags = "tags"

[[menu.main]]
weight = 1
name = "Home"
url = "/"

[[menu.main]]
weight = 2
name = "Services"
url = "/services/"
identifier = "services"
  [[menu.main]]
  parent = "services"
  weight = 1
  name = "Treatment Clinic"
  url = "/services/Treatment/"
  [[menu.main]]
  parent = "services"
  weight = 2
  name = "GP Clinic"
  url = "/services/GP/"
  [[menu.main]]
  parent = "services"
  weight = 3
  name = "Mental Health Care"
  url = "/services/MHC/"
  [[menu.main]]
  parent = "services"
  weight = 4
  name = "Counselling"
  url = "/services/Counselling/"
  [[menu.main]]
  parent = "services"
  weight = 5
  name = "Chaplaincy"
  url = "/services/Chaplaincy/"
  [[menu.main]]
  parent = "services"
  weight = 6
  name = "Housing"
  url = "/services/Housing/"
  [[menu.main]]
  parent = "services"
  weight = 7
  name = "Rehabilitation"
  url = "/services/Rehabilitation/"
  [[menu.main]]
  parent = "services"
  weight = 8
  name = "Support Groups"
  url = "/services/Support/"

[[menu.main]]
weight = 3
name = "About Us"
url = "/about/"
identifier = "about"
  [[menu.main]]
  parent = "about"
  weight = 1
  name = "Beginnings"
  url = "/about/Beginnings/"
  [[menu.main]]
  parent = "about"
  weight = 2
  name = "Beliefs and Values"
  url = "/about/Beliefs/"
  [[menu.main]]
  parent = "about"
  weight = 3
  name = "Leadership"
  url = "/about/Leadership/"
  [[menu.main]]
  parent = "about"
  weight = 4
  name = "Publications"
  url = "/about/Publications/"
  [[menu.main]]
  parent = "about"
  weight = 5
  name = "Subscribe"
  url = "/about/subscribe/"
  [[menu.main]]
  parent = "about"
  weight = 6
  name = "Accreditations"
  url = "/about/accreditations/"
  [[menu.main]]
  parent = "about"
  weight = 7
  name = "Privacy Statement"
  url = "/about/privacy/"

[[menu.main]]
weight = 4
name = "More items"
url = "/more/"
identifier = "more"
  [[menu.main]]
  parent = "more"
  weight = 1
  name = "Some more menu"
  url = "/more/some-more-menu/"
  [[menu.main]]
  parent = "more"
  weight = 2
  name = "items to show"
  url = "/more/items-to-show/"
  [[menu.main]]
  parent = "more"
  weight = 3
  name = "the nested menus feature"
  url = "/more/the-nested-menus-feature/"

[[menu.main]]
weight = 5
name = "Blog"
url = "/blog/"

[[menu.main]]
weight = 6
name = "Contact"
url = "/contact/"

[[menu.main]]
weight = 7
name = "Features"
url = "/features/"
identifier = "features"
  [[menu.main]]
  parent = "features"
  weight = 1
  name = "Responsive design"
  url = "/features/responsive-design/"
  [[menu.main]]
  parent = "features"
  weight = 2
  name = "Nested menus"
  url = "/features/nested-menus/"
  identifier = "nested-menus"
    [[menu.main]]
    parent = "nested-menus"
    weight = 1
    name = "Third level page #1"
    url = "/features/nested-menus/third-level-1/"
    [[menu.main]]
    parent = "nested-menus"
    weight = 2
    name = "Third level page #2"
    url = "/features/nested-menus/third-level-2/"
    [[menu.main]]
    parent = "nested-menus"
    weight = 3
    name = "Third level page #3"
    url = "/features/nested-menus/third-level-3/"
  [[menu.main]]
  parent = "features"
  weight = 3
  name = "Two-column layout"
  url = "/features/two-column-layout/"
  [[menu.main]]
  parent = "features"
  weight = 4
  name = "Tags"
  url = "/features/tags/"

